app = "geneco"
primary_region = "iad"
console_command = "python /code/manage.py shell"
kill_timeout = 120

[[vm]]
  size = "shared-cpu-1x"

[build]

[deploy]
  strategy = "rolling"
  release_command = "python /code/manage.py migrate"

[env]
  PORT = "8000"
  DJANGO_SETTINGS= "staging"
  DJANGO_SETTINGS_MODULE = "config.settings"

# [http_service]
[[services]]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
